services:
  slack-bot:
    build: .
    depends_on:
      infoseciitr-db:
        condition: service_healthy
    environment:
      - DB_HOST=infoseciitr-db
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASS=${DB_PASS}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 256M

  infoseciitr-db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  postgres_data: